Add missing return type for koffi.array
Hi,

Currently `array` function type declaration is missing return type, which causes a compilation error in TypeScript strict mode.

```
node_modules/koffi/src/koffi/src/index.d.ts:84:21 - error TS7010: 'array', which lacks return-type annotation, implicitly has an 'any' return type.
84     export function array(ref: TypeSpec, len: number, hint?: ArrayHint | null);
                       ~~~~~
```